project:
  type: website

website:
  title: "Nick Danis"
  favicon: icon.png
  navbar:
    search: false
    background: black
    right:
      - text: "About"
        href: index.qmd
      - teaching.qmd
      - research.qmd
      - publications.qmd
      - posts.qmd
      - cv.qmd


format:
  html:
    theme: 
      - journal
      - custom.scss
    css: styles.css
    toc: true
    toc-title: ""



