project:
  type: website

website:
  title: "Nick Danis"
  favicon: icon.png
  navbar:
    search: false
    background: white
    right:
      - teaching.qmd
      - research.qmd
      - publications.qmd
      - posts.qmd
      - cv.qmd


format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    toc-title: ""



